#!/bin/sh
. /home/igorhvr/idm/bedlam/tmp/dtclasspath
echo "(begin (define iasylum-bedlam-location \"/home/igorhvr/idm/bedlam/\") (load (string-append iasylum-bedlam-location \"iasylum/init.scm\"))) (nrepls) (let v () (j \"Thread.sleep(1000000);\") (v))" | java -DsocksProxyHost=localhost -DsocksProxyPort=8888 -Xmx1G clojure.main -e "(sisc.REPL/main (into-array [\"\"]))"
