#!/bin/bash
export JAVAOPT="-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=true -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.password.file=/base/bedlam/jmxremote.password -Dcom.sun.management.jmxremote.access.file=/base/bedlam/jmxremote.access"
/base/bedlam/sisc/sisc-1.16.6/sisc -e ' (begin (define iasylum-bedlam-location "/base/bedlam/") (load (string-append iasylum-bedlam-location "iasylum/init.scm")) "bedlam-enabled sisc started.")' "$@"
