#!/bin/bash
 /base/bedlam/sisc/sisc-1.16.6/sisc -x -e "(begin (define iasylum-bedlam-location \"/base/bedlam/\") (load (string-append iasylum-bedlam-location \"iasylum/init.scm\")))(j \"iu.M.i(3000, 3001);\")(let loop () (j \"Thread.sleep(Long.MAX_VALUE);\") (loop))"
