//noinspection HtmlUnknownTarget
dic = {
    'common': {
        'i18n': 'i18n',
        'source-list-separator': '------------------------------------',
        'exchange-rate-separator': '-------------------------------------------------------------------',
        'label-template': '<span class="label-color {0}">{1}</span>',
        'order-entry-buy': '<span class="{7}"><b>{6}</b></span> <span class="order-id">ID: {4}, {5}</span><br><span id="order-entry-{0}" class="order-entry">{1} <span class="arrow">&rarr;</span>&nbsp;{2} @<b class="buy">{3}</b></span>',
        'order-entry-sell': '<span class="{7}"><b>{6}</b></span> <span class="order-id">ID: {4}, {5}</span><br><span id="order-entry-{0}" class="order-entry">{1} @<b class="sell">{3}</b> <span class="arrow">&rarr;</span>&nbsp;{2}</span>',
        'order-pending-entry-buy': '<span class="{7}"><b>{6}</b></span>&nbsp;<span id="order-entry-{0}" class="order-entry-error">{1} <span class="arrow">&rarr;</span>&nbsp;{2} @<b class="buy">{3}</b></span>',
        'order-pending-entry-sell': '<span class="{7}"><b>{6}</b></span>&nbsp;<span id="order-entry-{0}" class="order-entry-error">{1} @<b class="sell">{3}</b> <span class="arrow">&rarr;</span>&nbsp;{2}</span>',
        'loading-small-template': '<img style="vertical-align: middle;" height="20" src="img/loader.gif" alt="Carregando...">'
    },
    'pt': {
        'the_language': 'pt-BR',
        'app_name': 'Walltime',
        'app_name_more': 'Walltime - {0}',
        'app_slogan': 'Você tem todo o tempo do turno.',
        'app_url': 'https://walltime.info/',
        'app_keywords': 'software,bitcoin,exchange',
        'app_description': 'Walltime Exchange. Buscamos colocar muita criatividade e excelência técnica a serviço de prover infraestrutura sólida para a vanguarda da economia digital.',
        'title_#!security-options' : 'senha & segurança',
        'title_#!account-statement' : 'extrato',
        'title_#!verify-account' : 'dados & verificação',
        'title_#!verify-account1' : 'dados básicos',
        'title_#!verify-account2' : 'documento de identidade',
        'title_#!verify-account3' : 'comprovante de residência',
        'title_#!orders' : 'ordens',
        'number-1000separator': '.',
        'number-decimal-separator': ',',
        'icon-alt-brl': 'Nota de real',
        'icon-alt-xbt': 'Moeda de bitcoin',
        'icon-title-brl': 'Reais (R$)',
        'icon-title-xbt': 'Bitcoin (BTC)',
        'currency-brl': 'R$',
        'currency-xbt': 'BTC',
        'currency-description-brl': 'Reais&nbsp;(R$)',
        'currency-description-xbt': 'Bitcoin&nbsp;(BTC)',
        'currency-short-description-brl': 'reais',
        'currency-short-description-xbt': 'bitcoin',
        'source-list-all': 'Tudo ({0})',
        'change-currency-brl': '⇋ BRL (R$)',
        'change-currency-xbt': '⇋ BTC&nbsp;',
        'change-from-brl-to-xbt': 'Trocar referência de Reais (BRL / R$) para Bitcoin (BTC)',
        'change-from-xbt-to-brl': 'Trocar referência de Bitcoin (BTC) para Reais (BRL / R$)',
        'loading': 'Carregando&hellip;',
        'order-book-title-total-brl': 'Total R$',
        'order-book-tooltip-total-brl': 'Volume total em reais',
        'order-book-title-total-xbt': 'Qtd. BTC',
        'order-book-tooltip-total-xbt': 'Volume total em bitcoin',
        'order-book-unit': 'Unidade',
        'order-book-unit-brl-xbt': 'Preço em R$ por cada unidade de bitcoin',
        'order-book-unit-xbt-brl': 'Preço em &micro;BTC por cada unidade de real',
        'market-info-content': 'Volume 24h: <b>{0}</b>{1}&nbsp;{2} &harr;&nbsp;{3}&nbsp;<b>{4}</b><span class="cents-volume">{5}</span>',
        'last-trades-title-diff-ult': 'Dif. últ.',
        'last-trades-tooltip-diff-ult': 'Diferença percentual em relação a ordem anterior executada',
        'last-trades-title-diff-24h': '24h',
        'last-trades-tooltip-diff-24h': 'Diferença percentual nas últimas 24h',
        'last-trades-title-time': 'Horário',
        'last-trades-tooltip-time': 'Data e horário {0}',
        'last-trades-round': 'Turno #{0}',
        'exchange-rate-pos0': 'Aprox. da melhor oferta de venda ({2})',
        'exchange-rate-pos1': 'Média entre compra e venda ({2})',
        'exchange-rate-pos2': 'Cobrir a melhor oferta de compra ({2})',
        'exchange-rate-pos3': 'Último valor negociado ({2})',
        'exchange-rate-pos4': 'IXBTC &ndash; Índice Brasileiro de Bitcoin ({2})',
        'exchange-rate-pos5': 'CoinDesk BPI &ndash; Bitcoin Price Index ({2})',
        'check-to-accept': 'Clique para concordar',
        'error-when-creating-account': 'Ocorreu algum erro ao criar sua conta. Por favor cheque cuidadosamente as informações.',
        'warn-level1': 'CONTA NÃO VERIFICADA: para aumentar seus limites atualmente bastante reduzidos, verifique sua conta agora mesmo.',
        'warn-level1-link': '#!verify-account',
        'warn-verifying': 'CONTA SENDO VERIFICADA: seus limites ainda estão reduzidos porque sua conta está em processo de verificação. Qualquer dúvida por favor entre em contato pelo email sos@walltime.info',
        'warn-pending-orders': 'ORDENS PENDENTES: uma ou mais ordens que criou não estão ativas por algum motivo.',
        'warn-pending-orders-link': '#orders',
        'warn-testnet': 'APENAS TESTE: Você está usando uma versão na rede TESTNET e não na rede principal do Bitcoin. Essa versão é destinada apenas para testes. Todos os valores mostrados aqui são totalmente fictícios. <em>Ambiente: {0}</em>',
        'warn-mockup': 'APENAS TESTE: Você está usando uma versão MOCKUP destinada apenas para testes. Todos os valores mostrados aqui são totalmente fictícios.',
        'warn-background-command-lost' : 'COMANDO PERDIDO: Havia um comando sendo executado em background quando você fez logout e não foi possível decodificar sua resposta.',
        'warn-out-of-date' : 'NOVA VERSÃO: Há uma nova versão disponível, por favor atualize com CTRL+SHIFT+R (você será deslogado).',
        'warn-out-of-date-link' : 'javascript:location.reload(true);',
        'warn-session-will-expire' : 'SESSÃO EXPIRANDO: Sua sessão vai expirar muito em breve. É recomendável que recarregue a página e faça login novamente agora para evitar que perca alguma coisa que esteja fazendo.',
        'warn-session-will-expire-link' : 'javascript:location.reload();',
        'label-active': 'ativa',
        'label-inactive': 'inativa',
        'label-sending-order': 'enviando&hellip;',
        'label-processing-order': 'em&nbsp;trânsito&hellip;',
        'try-cancel-order': 'Tentar cancelar ordem',
        'open-order-details': 'Mais detalhes da ordem',
        'label-waiting-user-order': 'aguardando&nbsp;ação&nbsp;do&nbsp;usuário',
        'label-user-requested-cancel-order': 'tentando&nbsp;cancelar&hellip;',
        'important-pending': 'Pendência importante! Clique para resolver.',
        'info-pending': 'Informação',
        'order-history': 'Histórico de execução da ordem',
        'order-entry-title': 'Clique para mostrar detalhes',
        'order-UNAUTHENTICATED_USER-problem': 'O usuário não está logado.',
        'order-UNAUTHENTICATED_USER-solution': 'fazer login ou criar conta',
        'order-UNAUTHENTICATED_USER-link': '#!fix-login',
        'order-NETWORK_ERROR-problem': 'Não foi possível enviar a ordem, falha na rede.',
        'order-NETWORK_ERROR-solution': 'tentar novamente agora',
        'order-NETWORK_ERROR-link': '#!sync-orders',
        'order-UNKNOWN_ERROR-problem': 'O servidor rejeitou a ordem por algum motivo.',
        'order-UNKNOWN_ERROR-solution': 'tentar novamente agora',
        'order-UNKNOWN_ERROR-link': '#!sync-orders',
        'label-new-order': 'nova',
        'label-waiting-walltime': 'aguardando&nbsp;Walltime',
        'order-MISSING_FUNDS-brl-problem': 'Não há saldo em reais suficiente.',
        'order-MISSING_FUNDS-brl-solution': 'deposite {0}',
        'order-MISSING_FUNDS-brl-link': '#!fix-deposit-brl?value={0}',
        'order-MISSING_FUNDS-xbt-problem': 'Não há saldo em bitcoin suficiente.',
        'order-MISSING_FUNDS-xbt-solution': 'deposite {0}',
        'order-MISSING_FUNDS-xbt-link': '#!fix-deposit-xbt?value={0}',
        'order-INVALID_INPUT-problem': 'Você digitou um número muito complexo. Ele não pode ter mais que 64 bits (18446744073709551616) no numerador ou denominador, e seu valor final precisa ser inferior a 32 bits (4294967296).',
        'order-INVALID_INPUT-solution': 'apague esta ordem',
        'order-INVALID_INPUT-link': 'javascript:wt.controller.tryCancelOrder("{0}");',
        'order-WAITING_CONFIRMATION-problem': 'A Walltime está confirmando seu depósito.',
        'order-WAITING_CONFIRMATION-solution': 'Se você já depositou, agora não precisa fazer mais nada, apenas relaxar e aguardar. Assim que '
        + 'o depósito for confirmado, sua ordem será automaticamente criada caso seu saldo seja suficiente. '
        + '<a href="#!verify-deposit-status">Verifique o status aqui</a>.',
        'order-WAITING_CONFIRMATION-link': '',
        'order-LIMBO_ERROR-problem': 'Ordem pendente no sistema.',
        'order-LIMBO_ERROR-solution': 'Sua ordem foi inicialmente aceita mas ainda está pendente em nosso sistema.' +
        ' Não é possível determinar se ela será aceita no futuro ou não. Se preferir, cancele esta ordem e crie uma nova ou '
        + 'entre em contato com o nosso suporte: <a href="mailto:sos@walltime.info?subject=Limbo order" target="email">sos@walltime.info</a>',
        'order-LIMBO_ERROR-link': '',
        'label-partial': '{0}&nbsp;executada',
        'label-completed-order': '&#10004;&nbsp;completa',
        'label-canceled-order': '&#10008;&nbsp;cancelada',
        'confirm-logout-with-queue': 'Você possui ordens locais pendentes. Ao fazer logout elas serão apagadas! Tem certeza?',
        'mandatory-source': 'Campo obrigatório',
        'mandatory-target': 'Campo obrigatório',
        'mandatory-ratio': 'Campo obrigatório',
        'priority-icon0': 'Execução rápida',
        'priority-icon1': 'Negociação',
        'priority-icon2': 'Negociação improvável',
        'priority-title': 'Quanto mais próximo do topo (porcentagens menores), mais provável que sua ordem seja executada.',
        'priority-title0': 'ORDEM RÁPIDA',
        'priority-title1': 'ORDEM NEGOCIADA',
        'priority-title2': 'ORDEM IMPROVÁVEL',
        'balance-title-brl': 'Saldo aproximado: {0}',
        'balance-title-xbt': 'Saldo aproximado: {0}',
        'unconfirmed-symbol' : '⌛️',
        'reserved-symbol' : '📗️️',
        'inactive-order-symbol' : '📙',
        'unconfirmed-balance-title': '{1} A confirmar: {0}',
        'reserved-balance-title': '{1} Reservado em ordens: {0}',
        'deposit0-alt': 'Depósito não identificado ainda.',
        'deposit1-alt': 'Depósito identificado, aguardando mais confirmações.',
        'deposit2-alt': 'Depósito confirmado.',
        'deposit0-xbt-text': 'Aguardando depósito. (<a class="external" target="info" title="Visualizar com BlockCypher™" href="https://live.blockcypher.com/{1}/address/{0}/">status</a>)',
        'deposit1-xbt-text': 'Depósito detectado. Aguardando mais confirmações: {0}&nbsp;de&nbsp;{1}&nbsp;confirmações.  (<a class="external" target="info" title="Visualizar com BlockCypher™" href="https://live.blockcypher.com/{3}/address/{2}/">status</a>)',
        'deposit2-xbt-text': 'Depósito confirmado em&nbsp;{1}.',
        'deposit0-brl-text': 'Seu depósito está sendo verificado.',
        'deposit2-brl-text': 'Depósito verificado em&nbsp;{1}.',
        'create-new-order-deposit-screen-sell': '(+) Criar ordem de venda de {0}...',
        'create-new-order-deposit-screen-buy': '(+) Criar ordem de compra de {0}...',
        'fingerprint-not-ready': 'A identificação do aplicativo não está pronta ainda. Por favor tente novamente.',
        'input-network-fee-xbt': 'Digite a taxa para mineração desejada (mín. 0,0003 BTC e máx. 0,001 BTC)',
        'input-network-fee-invalid': 'O valor "{0}" que digitou não é suportado. Verifique cuidadosamente o limite mínimo e máximo.',
        'withdraw-value-placeholder-xbt': 'valor em bitcoin (BTC)',
        'withdraw-value-placeholder-brl': 'valor em reais (R$) *',
        'withdraw-brl-account-format': '{0} ag. {1}{2} {3} {4}{5}',
        'withdraw-brl-account-type-cc': 'c/c',
        'withdraw-brl-account-type-cp': 'c/p',
        'solve': '<a href="{0}">(resolver)</a>',
        'data-label': 'Data',
        'statement-date-format': 'DD/MMM',
        'statement-hour-format': 'HH:mm',
        'standard-time-format': 'L HH:mm:ss',
        'entry-label': 'Lançamento',
        'statement-previous-balance-brl': '<b>Saldo anterior em reais (R$)</b>',
        'statement-previous-balance-xbt': '<b>Saldo anterior em bitcoin (BTC)</b>',
        'statement-deposit-brl': 'Depósito {0} em reais (R$)',
        'statement-deposit-xbt': 'Depósito {0} em bitcoin (BTC)',
        'statement-deposit-fee-brl': 'Taxa referente ao depósito {0}',
        'statement-deposit-fee-xbt': 'Taxa referente ao depósito {0}',
        'statement-day-balance-brl': 'Saldo do dia em reais (R$)',
        'statement-day-balance-xbt': 'Saldo do dia em bitcoin (BTC)',
        'statement-withdraw-brl': 'Retirada {0} em reais (R$)',
        'statement-withdraw-xbt': 'Retirada {0} em bitcoin (BTC)',
        'statement-withdraw-fee-brl': 'Taxa referente à retirada {0}',
        'statement-withdraw-fee-xbt': 'Taxa referente à retirada {0}',
        'statement-external-fee-brl': 'Taxa bancária (DOC, TED ou outros) referente à retirada {0}',
        'statement-external-fee-xbt': 'Taxa de mineração para manutenção da rede Bitcoin referente à retirada {0}',
        'statement-order-creation-brl': 'Criação de ordem {0}',
        'statement-order-creation-xbt': 'Criação de ordem {0}',
        'statement-order-partial-execution-brl': 'Execução parcial da ordem {0}',
        'statement-order-partial-execution-xbt': 'Execução parcial da ordem {0}',
        'statement-order-partial-execution-fee-brl': 'Taxa de execução parcial da ordem {0}',
        'statement-order-partial-execution-fee-xbt': 'Taxa de execução parcial da ordem {0}',
        'statement-order-complete-execution-brl': 'Execução total da ordem {0}',
        'statement-order-complete-execution-xbt': 'Execução total da ordem {0}',
        'statement-order-complete-execution-fee-brl': 'Taxa de execução da ordem {0}',
        'statement-order-complete-execution-fee-xbt': 'Taxa de execução da ordem {0}',
        'statement-order-cancellation-brl': 'Cancelamento da ordem {0}',
        'statement-order-cancellation-xbt': 'Cancelamento da ordem {0}',
        'statement-final-balance-brl': '<b>Saldo em reais (R$)</b>',
        'statement-final-balance-xbt': '<b>Saldo em bitcoin (BTC)</b>',
        'statement-simplification-gift-brl': 'Bônus de arredondamento relativo a execução da ordem {0}',
        'statement-simplification-gift-xbt': 'Bônus de arredondamento relativo a execução da ordem {0}',
        'entry-balance-label': 'Saldo',
        'entry-value-label': 'Valor',
        'exact-number': 'Valor exato:\n{0}➗{1}',
        'withdraw-status-pending': '🕓 PENDENTE, por favor aguarde.',
        'withdraw-status-sent-xbt': '✔ ENVIADO para <a class="external" target="info" title="Visualizar com BlockCypher™" href="https://live.blockcypher.com/{1}/address/{0}/">{0}</a>.',
        'withdraw-status-sent-brl': '✔ TRANSFERÊNCIA BANCÁRIA EFETUADA para {0}.',
        'withdraw-status-manual': '⛔ ️MODO MANUAL. <span class="tooltip" title="que preferimos não revelar agora por questão de segurança">Por algum motivo</span> seu pedido de saque não foi realizado de forma automática e será processado manualmente. Te enviaremos um email assim que for efetivado.',
        'withdraw-status-loading': '<span class="status">Verificando status&hellip;</span>',
        'exact-value-title': 'Saldo exato: {0}➗{1}',
        'invalid-order' : 'Ordem inválida. Por favor insira valores numéricos maiores que zero.',
        'failed-cancel-order' : 'Não foi possível cancelar a ordem {0}, por favor tente mais tarde.',
        'left-brl' : 'Quantidade que deseja trocar em reais (R$)',
        'left-xbt' : 'Quantidade que deseja trocar em bitcoin (BTC)',
        'right-brl' : 'Quantidade aproximada que deseja receber em reais (R$)',
        'right-xbt' : 'Quantidade aproximada que deseja receber em bitcoin (BTC)',
        'market-order-confirmation' : 'ATENÇÃO: Você está criando uma ordem A QUALQUER PREÇO.\n\nTEM CERTEZA QUE DESEJA CONTINUAR?',
        'file_too_big' : 'Esse arquivo é muito grande, maior que {0} MB.\n\nPor favor reduza o arquivo e tente novamente.',
        'file_too_small' : 'Esse arquivo é muito pequeno, menor que {0} KB.\n\nProvavelmente a resolução do documento está muito baixa.',
        'select_a_file_first' : 'Antes de prosseguir por favor selecione um arquivo logo acima.',
        'cannot-cancel-order-sync' : 'Não é possível cancelar enquanto as ordens são sincronizadas.',
        'no-balance-warn' : 'Acima do limite.',
        'low-withdraw-warn' : 'Abaixo do mínimo.',
        'new-address-info-xbt' : 'NOTA IMPORTANTE: Para sua própria segurança, ao cadastrar um novo endereço para saque ele começa com limites baixos que vão aumentando com o passar do tempo. Veja <a class="external" target="info" href="#!text?content=seguranca-e-limites">segurança e limites</a>. Ele começa bloqueado até que nossa equipe possa confirmar com você por telefone a intenção de cadastrar um novo endereço.',
        'new-address-info-brl' : 'NOTA IMPORTANTE: Para sua própria segurança, ao cadastrar uma nova conta para saque ela começa com limites baixos que vão aumentando com o passar do tempo. Veja <a class="external" target="info" href="#!text?content=seguranca-e-limites">segurança e limites</a>. Ele começa bloqueado até que nossa equipe possa confirmar com você por telefone a intenção de cadastrar uma nova conta.',
        'first-address-info-xbt' : 'NOTA: Este é seu primeiro endereço de saída a ser cadastrado e ele já inicia com o limite máximo. Veja <a class="external" target="info" href="#!text?content=seguranca-e-limites">segurança e limites</a>. Escolha com cuidado porque o cadastro de novos endereços é desencorajado pela Walltime.',
        'first-address-info-brl' : 'NOTA: Esta é sua primeira conta bancária e ela já inicia com o limite máximo. Veja <a class="external" target="info" href="#!text?content=seguranca-e-limites">segurança e limites</a>. Escolha com cuidado porque o cadastro de novas contas é desencorajado pela Walltime.',
        'withdraw-submenu' : 'Retirada',
        'withdraw-submenu-new-xbt' : 'Novo endereço',
        'withdraw-submenu-new-brl' : 'Nova conta',
        'new-withdraw-account-entry-brl-disabled' : 'Por segurança, não é possível cadastrar novas contas de saída sem antes verificar sua conta.',
        'new-withdraw-account-entry-brl-enabled-first' : 'Sua primeira conta cadastrada inicia no limite máximo.',
        'new-withdraw-account-entry-brl-enabled-new' : 'Por segurança, contas adicionais começarão com limites reduzidos e precisarão ser confirmadas por telefone.',
        'new-withdraw-account-entry-xbt-disabled' : 'Por segurança, não é possível cadastrar novos endereços de saída sem antes verificar sua conta.',
        'new-withdraw-account-entry-xbt-enabled-first' : 'Seu primeiro endereço cadastrado inicia no limite máximo.',
        'new-withdraw-account-entry-xbt-enabled-new' : 'Por segurança, endereços adicionais começarão com limites reduzidos e precisarão ser confirmados por telefone.',
        'text-title-seguranca-e-limites' : 'Segurança e limites',
        'text-title-termos-de-uso' : 'Termos de uso',
        'text-title-taxas' : 'Taxas',
        'text-title-ajuda' : 'Ajuda',
        'text-title-licenses' : 'Licenças utilizadas',
        'text-title-changelog' : 'Detalhes da versão (em inglês)',
        'text-title-privacidade' : 'Política de privacidade',
        'more-than-one-file-alert' : 'Envie apenas um arquivo!'
    }
};